<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-LIJIBR5S" failures="1" tests="3" name="Stand Alone Test" time="34.494" errors="0" timestamp="2025-09-06T17:07:34 IST">
  <testcase classname="VinitCom.tests.StandAloneTest" name="SubmitOrder" time="14.51">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at VinitCom.tests.StandAloneTest.SubmitOrder(StandAloneTest.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- SubmitOrder -->
  <testcase classname="VinitCom.tests.StandAloneTest" name="SubmitOrder" time="9.891"/>
  <testcase classname="VinitCom.tests.StandAloneTest" name="verifyOrderHistory" time="0.0">
    <skipped/>
  </testcase> <!-- verifyOrderHistory -->
</testsuite> <!-- Stand Alone Test -->
