<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="1" failed="3" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-07T15:57:51 IST" name="Suite" finished-at="2025-09-07T15:58:43 IST" duration-ms="51682">
    <groups>
      <group name="Purchase">
        <method signature="StandAloneTest.SubmitOrder(java.util.HashMap)[pri:0, instance:VinitCom.tests.StandAloneTest@239a307b]" name="SubmitOrder" class="VinitCom.tests.StandAloneTest"/>
      </group> <!-- Purchase -->
      <group name="Error">
        <method signature="ErrorValidation.productErrorValidation()[pri:0, instance:VinitCom.tests.ErrorValidation@13d73f29]" name="productErrorValidation" class="VinitCom.tests.ErrorValidation"/>
      </group> <!-- Error -->
    </groups>
    <test started-at="2025-09-07T15:57:51 IST" name="Error Validation" finished-at="2025-09-07T15:58:31 IST" duration-ms="40605">
      <class name="VinitCom.tests.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:VinitCom.tests.ErrorValidation@13d73f29]" started-at="2025-09-07T15:57:51 IST" name="launchApplication" finished-at="2025-09-07T15:57:58 IST" duration-ms="7032" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:VinitCom.tests.ErrorValidation@13d73f29]" started-at="2025-09-07T15:57:58 IST" name="loginErrorValidation" finished-at="2025-09-07T15:58:00 IST" duration-ms="1849" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [[[ChromeDriver: chrome on windows (d25f329a831a4b067cd4dbd8c2c0a021)] -> css selector: [class*='flyInOut']] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [[[ChromeDriver: chrome on windows (d25f329a831a4b067cd4dbd8c2c0a021)] -> css selector: [class*='flyInOut']] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:644)
at VinitCom.tests.ErrorValidation.loginErrorValidation(ErrorValidation.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:VinitCom.tests.ErrorValidation@13d73f29]" started-at="2025-09-07T15:58:01 IST" name="tearDown" finished-at="2025-09-07T15:58:01 IST" duration-ms="674" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:VinitCom.tests.ErrorValidation@13d73f29]" started-at="2025-09-07T15:58:01 IST" name="launchApplication" finished-at="2025-09-07T15:58:06 IST" duration-ms="5043" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="productErrorValidation()[pri:0, instance:VinitCom.tests.ErrorValidation@13d73f29]" started-at="2025-09-07T15:58:06 IST" name="productErrorValidation" finished-at="2025-09-07T15:58:14 IST" duration-ms="7745" status="SKIP">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "DesiredProd" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "DesiredProd" is null
at VinitCom.pagebjects.ProductCatalog.addProductToCart(ProductCatalog.java:57)
at VinitCom.tests.ErrorValidation.productErrorValidation(ErrorValidation.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:VinitCom.tests.ErrorValidation@13d73f29]" started-at="2025-09-07T15:58:14 IST" name="tearDown" finished-at="2025-09-07T15:58:14 IST" duration-ms="223" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:VinitCom.tests.ErrorValidation@13d73f29]" started-at="2025-09-07T15:58:14 IST" name="launchApplication" finished-at="2025-09-07T15:58:22 IST" duration-ms="7151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:VinitCom.tests.ErrorValidation@13d73f29]" started-at="2025-09-07T15:58:22 IST" name="productErrorValidation" finished-at="2025-09-07T15:58:29 IST" duration-ms="7670" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "DesiredProd" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "DesiredProd" is null
at VinitCom.pagebjects.ProductCatalog.addProductToCart(ProductCatalog.java:57)
at VinitCom.tests.ErrorValidation.productErrorValidation(ErrorValidation.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:VinitCom.tests.ErrorValidation@13d73f29]" started-at="2025-09-07T15:58:30 IST" name="tearDown" finished-at="2025-09-07T15:58:31 IST" duration-ms="1883" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- VinitCom.tests.ErrorValidation -->
    </test> <!-- Error Validation -->
    <test started-at="2025-09-07T15:57:51 IST" name="Stand Alone Test" finished-at="2025-09-07T15:58:43 IST" duration-ms="51682">
      <class name="VinitCom.tests.StandAloneTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:VinitCom.tests.StandAloneTest@239a307b]" started-at="2025-09-07T15:57:51 IST" name="launchApplication" finished-at="2025-09-07T15:57:59 IST" duration-ms="8014" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:VinitCom.tests.StandAloneTest@239a307b]" started-at="2025-09-07T15:57:59 IST" name="SubmitOrder" data-provider="getData" finished-at="2025-09-07T15:58:24 IST" duration-ms="24936" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Vinit@123, product=ADIDAS ORIGINAL, email=vinit123@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at VinitCom.tests.StandAloneTest.SubmitOrder(StandAloneTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:VinitCom.tests.StandAloneTest@239a307b]" started-at="2025-09-07T15:58:24 IST" name="tearDown" finished-at="2025-09-07T15:58:25 IST" duration-ms="824" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:VinitCom.tests.StandAloneTest@239a307b]" started-at="2025-09-07T15:58:25 IST" name="launchApplication" finished-at="2025-09-07T15:58:31 IST" duration-ms="5848" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:VinitCom.tests.StandAloneTest@239a307b]" started-at="2025-09-07T15:58:31 IST" name="SubmitOrder" data-provider="getData" finished-at="2025-09-07T15:58:42 IST" duration-ms="10546" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sujal@14325, product=IPHONE 13 PRO, email=Sujal123@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:VinitCom.tests.StandAloneTest@239a307b]" started-at="2025-09-07T15:58:42 IST" name="tearDown" finished-at="2025-09-07T15:58:43 IST" duration-ms="702" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="verifyOrderHistory()[pri:0, instance:VinitCom.tests.StandAloneTest@239a307b]" started-at="2025-09-07T15:58:43 IST" name="verifyOrderHistory" finished-at="2025-09-07T15:58:43 IST" depends-on-methods="VinitCom.tests.StandAloneTest.SubmitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VinitCom.tests.StandAloneTest.verifyOrderHistory() on instance VinitCom.tests.StandAloneTest@239a307b depends on not successfully finished methods 
[VinitCom.tests.StandAloneTest.SubmitOrder() on instance VinitCom.tests.StandAloneTest@239a307b]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VinitCom.tests.StandAloneTest.verifyOrderHistory() on instance VinitCom.tests.StandAloneTest@239a307b depends on not successfully finished methods 
[VinitCom.tests.StandAloneTest.SubmitOrder() on instance VinitCom.tests.StandAloneTest@239a307b]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyOrderHistory -->
      </class> <!-- VinitCom.tests.StandAloneTest -->
    </test> <!-- Stand Alone Test -->
  </suite> <!-- Suite -->
</testng-results>
